### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by eziwen** [JessYanCoding/RetrofitUrlManager#18]
机型：华为H60-L01  系统：Android4.4.2
java.lang.ExceptionInInitializerError
	at me.jessyan.retrofiturlmanager.RetrofitUrlManager.getInstance(RetrofitUrlManager.java:91)
	at come.sina.show.net.NetClient.<init>(NetClient.java:65)
	at come.sina.show.net.NetClient.<init>(NetClient.java:22)
	at come.sina.show.net.NetClient$SingletonHolder.<clinit>(NetClient.java:77)
	at come.sina.show.net.NetClient.getInstance(NetClient.java:85)
	at come.sina.show.f.r.<init>(MainPresenter.java:33)
	at come.sina.show.activity.MainActivity.r(MainActivity.java:92)
	at come.sina.show.activity.BaseActivity.onCreate(BaseActivity.java:59)
	at android.app.Activity.performCreate(Activity.java:5285)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2259)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2345)
	at android.app.ActivityThread.access$1100(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5314)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: Must be dependency Okhttp
	at me.jessyan.retrofiturlmanager.RetrofitUrlManager.<init>(RetrofitUrlManager.java:73)
	at me.jessyan.retrofiturlmanager.RetrofitUrlManager.<init>(RetrofitUrlManager.java:46)
	at me.jessyan.retrofiturlmanager.RetrofitUrlManager$RetrofitUrlManagerHolder.<clinit>(RetrofitUrlManager.java:87)
	... 22 more
java.lang.IllegalStateException: Must be dependency Okhttp
	at me.jessyan.retrofiturlmanager.RetrofitUrlManager.<init>(RetrofitUrlManager.java:73)
	at me.jessyan.retrofiturlmanager.RetrofitUrlManager.<init>(RetrofitUrlManager.java:46)
	at me.jessyan.retrofiturlmanager.RetrofitUrlManager$RetrofitUrlManagerHolder.<clinit>(RetrofitUrlManager.java:87)
	at me.jessyan.retrofiturlmanager.RetrofitUrlManager.getInstance(RetrofitUrlManager.java:91)
	at come.sina.show.net.NetClient.<init>(NetClient.java:65)
	at come.sina.show.net.NetClient.<init>(NetClient.java:22)
	at come.sina.show.net.NetClient$SingletonHolder.<clinit>(NetClient.java:77)
	at come.sina.show.net.NetClient.getInstance(NetClient.java:85)
	at come.sina.show.f.r.<init>(MainPresenter.java:33)
	at come.sina.show.activity.MainActivity.r(MainActivity.java:92)
	at come.sina.show.activity.BaseActivity.onCreate(BaseActivity.java:59)
	at android.app.Activity.performCreate(Activity.java:5285)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2259)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2345)
	at android.app.ActivityThread.access$1100(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5314)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by JessYanCoding** [comment]
Must be dependency Okhttp
